**❓ What is Pandas**

Pandas is a Python library used for loading, cleaning, and analyzing data. It provides easy to use tools like Series and DataFrames for working with structured datasets.

**⚙️ Why Pandas is Important in Machine Learning**

Pandas is the **go-to library for data manipulation and analysis** in Machine Learning.  
It is built on top of NumPy and provides easy-to-use data structures like **Series** and **DataFrame**.

**🔍 Why Pandas is Essential:**
- 📂 **Data Handling:** Load, clean, and preprocess real-world datasets (CSV, Excel, SQL, JSON).
- 🧭 **Data Exploration:** Understand your data — structure, missing values, correlations.
- ⚙️ **Integration with ML:** Works seamlessly with Scikit-Learn, NumPy, Matplotlib, and Seaborn.
- 📈 **Feature Engineering:** Create, transform, and select useful features for models.
- 🔢 **Efficient Operations:** Built on NumPy, so it’s fast and memory-efficient.

> 💡 *Pandas turns messy, raw data into clean, model-ready data.*

---

**Install Pnadas and import it**

In [1]:
%pip install -U -q pandas

[notice] A new release of pip is available: 25.1.1 -> 25.3
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [2]:
import pandas as pd

**Series (1D data)**

In [57]:
s = pd.Series([10, 20, 30, 40, 50], name="Marks")

In [58]:
print(type(s))

<class 'pandas.core.series.Series'>

In [59]:
print(s)

0    10
1    20
2    30
3    40
4    50
Name: Marks, dtype: int64

In [60]:
print(s[0])
print(s.mean())

10
30.0

**DataFrame (2D Data)**

In [61]:
data = {
    "Name": ['Alice', 'Bob', 'Charlie', 'David'],
    "Age": [24, 27, 22, 32],
    "Score": [85, 91, 78, 88]
}

data_frame = pd.DataFrame(data)

In [62]:
print(type(data_frame))

<class 'pandas.core.frame.DataFrame'>

In [63]:
print(data_frame)

      Name  Age  Score
0    Alice   24     85
1      Bob   27     91
2  Charlie   22     78
3    David   32     88

In [64]:
data_frame.head()  # data_frame.tail()

      Name  Age  Score
0    Alice   24     85
1      Bob   27     91
2  Charlie   22     78
3    David   32     88

In [65]:
# saving a dataframe to a csv file
data_frame.to_csv("data_sample.csv", index=False)

**Read Data from a csv file**

In [66]:
diabetes_df = pd.read_csv("diabetes.csv")

In [67]:
diabetes_df.shape

(768, 9)

In [68]:
diabetes_df.columns

Index(['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin',
       'BMI', 'DiabetesPedigreeFunction', 'Age', 'Outcome'],
      dtype='object')

In [69]:
diabetes_df.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [70]:
diabetes_df.tail()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
763,10,101,76,48,180,32.9,0.171,63,0
764,2,122,70,27,0,36.8,0.340,27,0
765,5,121,72,23,112,26.2,0.245,30,0
766,1,126,60,0,0,30.1,0.349,47,1
767,1,93,70,31,0,30.4,0.315,23,0

In [71]:
# read data_sample.csv and analyse it
df = pd.read_csv("data_sample.csv")

In [72]:
df.shape

(4, 3)

In [73]:
df

      Name  Age  Score
0    Alice   24     85
1      Bob   27     91
2  Charlie   22     78
3    David   32     88

In [74]:
df.head() # first 5 rows in the dataframe

      Name  Age  Score
0    Alice   24     85
1      Bob   27     91
2  Charlie   22     78
3    David   32     88

In [75]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    4 non-null      object
 1   Age     4 non-null      int64
 2   Score   4 non-null      int64
dtypes: int64(2), object(1)
memory usage: 228.0+ bytes

**Inspecting the data**

In [76]:
print("Shape:", df.shape)
print("\nColumns:", df.columns)
print("\nData Types:\n", df.dtypes)

Shape: (4, 3)

Columns: Index(['Name', 'Age', 'Score'], dtype='object')

Data Types:
 Name     object
Age       int64
Score     int64
dtype: object

**Selecting the data**

In [77]:
# single column
print(df["Name"])

0      Alice
1        Bob
2    Charlie
3      David
Name: Name, dtype: object

In [78]:
# multiple columns
print(df[["Name", "Age"]])

      Name  Age
0    Alice   24
1      Bob   27
2  Charlie   22
3    David   32

In [ ]:
# row selection
print(df.iloc[1]) # by position of row

Name     Bob
Age       27
Score     91
Name: 1, dtype: object

In [ ]:
print(df.loc[1]) # label

Name     Bob
Age       27
Score     91
Name: 1, dtype: object

In [84]:
data = {
    'Name': ['Anna', 'Ben', 'Cara', 'Dan'],
    'Score': [88, 92, 95, 70]
}

sample_df_2 = pd.DataFrame(data, index=["a", "b", "c", "d"])

In [85]:
sample_df_2.head()

   Name  Score
a  Anna     88
b   Ben     92
c  Cara     95
d   Dan     70

In [86]:
sample_df_2.iloc[1]

Name     Ben
Score     92
Name: b, dtype: object

In [89]:
sample_df_2.loc["b"]

Name     Ben
Score     92
Name: b, dtype: object

**Filtering Data**

In [90]:
df

      Name  Age  Score
0    Alice   24     85
1      Bob   27     91
2  Charlie   22     78
3    David   32     88

In [91]:
high_scores = df[df["Score"] > 85]
print(high_scores)

    Name  Age  Score
1    Bob   27     91
3  David   32     88

In [93]:
low_scores = df[df["Score"] <= 85]
print(low_scores)

      Name  Age  Score
0    Alice   24     85
2  Charlie   22     78

**Adding new column**

In [94]:
df["Passed"] = df["Score"] > 80
print(df)

      Name  Age  Score  Passed
0    Alice   24     85    True
1      Bob   27     91    True
2  Charlie   22     78   False
3    David   32     88    True

In [95]:
df["Score_Percentage"] = df["Score"] / 100 * 100

In [96]:
df

      Name  Age  Score  Passed  Score_Percentage
0    Alice   24     85    True              85.0
1      Bob   27     91    True              91.0
2  Charlie   22     78   False              78.0
3    David   32     88    True              88.0

In [97]:
df["City"] = ["New York", "Boston", "Florida", "California"]

In [98]:
df

      Name  Age  Score  Passed  Score_Percentage        City
0    Alice   24     85    True              85.0    New York
1      Bob   27     91    True              91.0      Boston
2  Charlie   22     78   False              78.0     Florida
3    David   32     88    True              88.0  California

**Descriptive Statistics**

In [100]:
print("Average Score:", df["Score"].mean())
print("Max Score:", df["Score"].max())
print("Min Score:", df["Score"].min())

Average Score: 85.5
Max Score: 91
Min Score: 78

In [101]:
df.describe()

             Age      Score  Score_Percentage
count   4.000000   4.000000          4.000000
mean   26.250000  85.500000         85.500000
std     4.349329   5.567764          5.567764
min    22.000000  78.000000         78.000000
25%    23.500000  83.250000         83.250000
50%    25.500000  86.500000         86.500000
75%    28.250000  88.750000         88.750000
max    32.000000  91.000000         91.000000

**Handling missing data**

In [102]:
df2 = pd.DataFrame({
    'Name': ['Alice', 'Bob', 'Charlie', None],
    'Age': [24, None, 22, 32],
    'Score': [85, 91, None, 88]
})

In [103]:
df2.head()

      Name   Age  Score
0    Alice  24.0   85.0
1      Bob   NaN   91.0
2  Charlie  22.0    NaN
3     None  32.0   88.0

In [105]:
df2.dropna(subset=["Name"], inplace=True)

In [106]:
df2.head()

      Name   Age  Score
0    Alice  24.0   85.0
1      Bob   NaN   91.0
2  Charlie  22.0    NaN

In [107]:
df2["Age"] = df2["Age"].fillna(df2["Age"].mean())
df2["Score"] = df2["Score"].fillna(df2["Score"].mean())

In [108]:
df2.head()

      Name   Age  Score
0    Alice  24.0   85.0
1      Bob  23.0   91.0
2  Charlie  22.0   88.0