In [1]:
import numpy as np 
import pandas as pd

### Series ==> 1D Array (Vector)

In [2]:
s = pd.Series([10,20,30,40,50,60], name="Marks")

In [3]:
print(type(s))

<class 'pandas.Series'>

In [4]:
s[0]

np.int64(10)

In [5]:
s.mean()

np.float64(35.0)

### DataFrame ==> 2D (Matrix)

In [6]:
data = {
    "Name" : ["Dami", "Bob", "Shola"],
    "Age" : [10,25,27],
    "Score" : [50, 60, 70]
}

In [7]:
dataFrame = pd.DataFrame(data)

In [8]:
print(type(dataFrame))

<class 'pandas.DataFrame'>

### Saving To CSV File

In [9]:
dataFrame.to_csv("data_sample.csv", index = False)

### Loading a CSV File

In [10]:
diabetes = pd.read_csv(r'C:\Users\AYO_AYO\Desktop\Bluechip_Machine_Learning\Udemy - ML\Dataset\diabetes.csv')

In [11]:
diabetes

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1
...,...,...,...,...,...,...,...,...,...
763,10,101,76,48,180,32.9,0.171,63,0
764,2,122,70,27,0,36.8,0.340,27,0
765,5,121,72,23,112,26.2,0.245,30,0
766,1,126,60,0,0,30.1,0.349,47,1
767,1,93,70,31,0,30.4,0.315,23,0

In [12]:
diabetes.info

<bound method DataFrame.info of      Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6
1              1       85             66             29        0  26.6
2              8      183             64              0        0  23.3
3              1       89             66             23       94  28.1
4              0      137             40             35      168  43.1
..           ...      ...            ...            ...      ...   ...
763           10      101             76             48      180  32.9
764            2      122             70             27        0  36.8
765            5      121             72             23      112  26.2
766            1      126             60              0        0  30.1
767            1       93             70             31        0  30.4

     DiabetesPedigreeFunction  Age  Outcome
0                       0.627   50        1
1                       0.351   31        0
2                       0.672   32        1
3                       0.167   21        0
4                       2.288   33        1
..                        ...  ...      ...
763                     0.171   63        0
764                     0.340   27        0
765                     0.245   30        0
766                     0.349   47        1
767                     0.315   23        0

[768 rows x 9 columns]>

In [13]:
diabetes.shape

(768, 9)

In [14]:
diabetes.columns

Index(['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin',
       'BMI', 'DiabetesPedigreeFunction', 'Age', 'Outcome'],
      dtype='str')

In [15]:
diabetes.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [16]:
diabetes.tail()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
763,10,101,76,48,180,32.9,0.171,63,0
764,2,122,70,27,0,36.8,0.340,27,0
765,5,121,72,23,112,26.2,0.245,30,0
766,1,126,60,0,0,30.1,0.349,47,1
767,1,93,70,31,0,30.4,0.315,23,0

### Read data_sample.csv

In [17]:
df = pd.read_csv('data_sample.csv')

In [18]:
# df.columns = ["num", "name", "mark"]
df.columns

Index(['Name', 'Age', 'Score'], dtype='str')

In [19]:
df.shape

(3, 3)

In [20]:
df.info(memory_usage=True)

<class 'pandas.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    3 non-null      str
 1   Age     3 non-null      int64
 2   Score   3 non-null      int64
dtypes: int64(2), str(1)
memory usage: 204.0 bytes

In [21]:
print("Data Shape\n", df.shape, "\n")
print("Data Type\n", df.dtypes, "\n")
print("Data Columns\n", df.columns)

Data Shape
 (3, 3)

Data Type
 Name       str
Age      int64
Score    int64
dtype: object

Data Columns
 Index(['Name', 'Age', 'Score'], dtype='str')

### Selecting The Data

In [22]:
# Single Column = Series / Vector
df["Name"]

0     Dami
1      Bob
2    Shola
Name: Name, dtype: str

In [23]:
# Multiple Column / Multiple Series = DataFrame
df[["Age", "Score"]]

   Age  Score
0   10     50
1   25     60
2   27     70

In [24]:
# Row Selection
(df.iloc[1]) # by index

Name     Bob
Age       25
Score     60
Name: 1, dtype: object

In [25]:
df.loc[0] # by label
# Go to row index 0 and fetch me all the data

Name     Dami
Age        10
Score      50
Name: 0, dtype: object

In [26]:
df.set_index("Name", inplace=True)

In [27]:
df.loc["Dami"]
# Go through the "Name" index column and fetch all the data for row that matches "Bob"

Age      10
Score    50
Name: Dami, dtype: int64

In [28]:
students = {
    "ID": [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
    "Name": ["Alice", "Bob", "John", "Mary", "David", "Sophia", "Daniel", "Emma", "Chris", "Olivia"],
    "Age": [20, 22, 19, 21, 23, 20, 22, 19, 24, 21],
    "Score": [85, 90, 78, 88, 92, 95, 80, 76, 89, 91],
    "Gender": ["F", "M", "M", "F", "M", "F", "M", "F", "M", "F"],
    "Department": ["CS", "Math", "Physics", "Biology", "CS", "Math", "Physics", "Biology", "CS", "Math"]
}

students_df = pd.DataFrame(students)

In [29]:
students_df

   ID    Name  Age  Score Gender Department
0   1   Alice   20     85      F         CS
1   2     Bob   22     90      M       Math
2   3    John   19     78      M    Physics
3   4    Mary   21     88      F    Biology
4   5   David   23     92      M         CS
5   6  Sophia   20     95      F       Math
6   7  Daniel   22     80      M    Physics
7   8    Emma   19     76      F    Biology
8   9   Chris   24     89      M         CS
9  10  Olivia   21     91      F       Math

In [30]:
students_df.columns = students_df.columns.str.lower()

In [31]:
students_df.columns

Index(['id', 'name', 'age', 'score', 'gender', 'department'], dtype='str')

### Filtering Data

In [32]:
older_students = (students_df["age"] >= 22) & (students_df["gender"] == "M")
students_df[older_students]

   id    name  age  score gender department
1   2     Bob   22     90      M       Math
4   5   David   23     92      M         CS
6   7  Daniel   22     80      M    Physics
8   9   Chris   24     89      M         CS

### Creating New Columns

In [33]:
students_df["passed"] = students_df["score"] > 80

students_df

   id    name  age  score gender department  passed
0   1   Alice   20     85      F         CS    True
1   2     Bob   22     90      M       Math    True
2   3    John   19     78      M    Physics   False
3   4    Mary   21     88      F    Biology    True
4   5   David   23     92      M         CS    True
5   6  Sophia   20     95      F       Math    True
6   7  Daniel   22     80      M    Physics   False
7   8    Emma   19     76      F    Biology   False
8   9   Chris   24     89      M         CS    True
9  10  Olivia   21     91      F       Math    True

In [34]:
low_scores = students_df[students_df["score"] <= 80]
low_scores

   id    name  age  score gender department  passed
2   3    John   19     78      M    Physics   False
6   7  Daniel   22     80      M    Physics   False
7   8    Emma   19     76      F    Biology   False

In [35]:
students_df['score_%'] = students_df['score'].mul(100).round(2) / 100

In [36]:
states = [
    "Kano",
    "Enugu",
    "Ondo",
    "Bauchi",
    "Akwa Ibom",
    "Kwara",
    "Taraba",
    "Ekiti",
    "Nasarawa",
    "Zamfara"
]

students_df["city"] = states

In [37]:
students_df

   id    name  age  score gender department  passed  score_%       city
0   1   Alice   20     85      F         CS    True     85.0       Kano
1   2     Bob   22     90      M       Math    True     90.0      Enugu
2   3    John   19     78      M    Physics   False     78.0       Ondo
3   4    Mary   21     88      F    Biology    True     88.0     Bauchi
4   5   David   23     92      M         CS    True     92.0  Akwa Ibom
5   6  Sophia   20     95      F       Math    True     95.0      Kwara
6   7  Daniel   22     80      M    Physics   False     80.0     Taraba
7   8    Emma   19     76      F    Biology   False     76.0      Ekiti
8   9   Chris   24     89      M         CS    True     89.0   Nasarawa
9  10  Olivia   21     91      F       Math    True     91.0    Zamfara

In [38]:
# Drop a column
students_df.drop(columns = ['score_%'], inplace=True)

### Descriptive statistics

In [39]:
print(f"Average score: {students_df['score'].mean()}")
print(f"Maximum score: {students_df['score'].max()}")
print(f"Minimum score: {students_df['score'].min()}")

Average score: 86.4
Maximum score: 95
Minimum score: 76

In [40]:
students_df.describe()

             id       age     score
count  10.00000  10.00000  10.00000
mean    5.50000  21.10000  86.40000
std     3.02765   1.66333   6.41526
min     1.00000  19.00000  76.00000
25%     3.25000  20.00000  81.25000
50%     5.50000  21.00000  88.50000
75%     7.75000  22.00000  90.75000
max    10.00000  24.00000  95.00000

**Handling Missing Data**

In [41]:
data = {
    "name": ["Alice", "Bob", None, "David", "Eve"],
    "age": [25, np.nan, 30, None, 22],
    "score": [85, 90, np.nan, 88, None]
}

sample_df = pd.DataFrame(data)

In [42]:
# Droping Null Values
sample_df.dropna(subset = "name", inplace = True)

In [43]:
sample_df

    name   age  score
0  Alice  25.0   85.0
1    Bob   NaN   90.0
3  David   NaN   88.0
4    Eve  22.0    NaN

In [44]:
sample_df['age'] = sample_df['age'].fillna(sample_df['age'].mean())
sample_df['score'] = sample_df['score'].fillna(sample_df['score'].mean().round(2))

In [45]:
sample_df["score"].mean()

np.float64(87.6675)

In [46]:
sample_df

    name   age  score
0  Alice  25.0  85.00
1    Bob  23.5  90.00
3  David  23.5  88.00
4    Eve  22.0  87.67