In [2]:
# %pip install -q scikit-learn

In [3]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
import warnings

warnings.filterwarnings("ignore")
pd.set_option("display.max_columns", None)

**Load the dataset**

In [4]:
try:
    FILE_PATH = r"C:\Users\AYO_AYO\Desktop\Machine-Learning-Bootcamp\CSV-Excel\Datasets\titanic_dataset.csv"
    titanic_df = pd.read_csv(FILE_PATH)
    print("Dataset loaded succesfully")
except FileNotFoundError as e:
    print("Dataset not found", e)

Dataset loaded succesfully

In [5]:
titanic_df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [6]:
row, column = titanic_df.shape
print(f"Row: {row}, Column: {column}")

Row: 891, Column: 15

**Dropping Repeated Columns**

In [7]:
titanic_df.drop(columns=["who","alive"], inplace=True)
row, column = titanic_df.shape
print(f"Row: {row}, Column: {column}")

Row: 891, Column: 13

**Dropping Rows with Null/Missing values**

In [8]:
target_column = "survived"

missing_target_count = titanic_df[target_column].isna().sum()
print("Row with missing target", missing_target_count)

# Dropping the missing target row
titanic_df.dropna(subset=[target_column], inplace=True)
print("Shape after dropping row", titanic_df.shape)

Row with missing target 0
Shape after dropping row (891, 13)

In [9]:
titanic_df

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,adult_male,deck,embark_town,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,True,NaN,Southampton,False
1,1,1,female,38.0,1,0,71.2833,C,First,False,C,Cherbourg,False
2,1,3,female,26.0,0,0,7.9250,S,Third,False,NaN,Southampton,True
3,1,1,female,35.0,1,0,53.1000,S,First,False,C,Southampton,False
4,0,3,male,35.0,0,0,8.0500,S,Third,True,NaN,Southampton,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,True,NaN,Southampton,True
887,1,1,female,19.0,0,0,30.0000,S,First,False,B,Southampton,True
888,0,3,female,NaN,1,2,23.4500,S,Third,False,NaN,Southampton,False
889,1,1,male,26.0,0,0,30.0000,C,First,True,C,Cherbourg,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,True,NaN,Queenstown,True

**Separating dataframe into feature and target**

In [10]:
X = titanic_df.drop(columns=[target_column], axis=1)
y = titanic_df[target_column]

print("Features Shape", X.shape)
print("Target Shape", y.shape)

Features Shape (891, 12)
Target Shape (891,)

**Target Distribution** (Classification)

In [11]:
print("Target distribution")
print(y.value_counts())

print("*"*20)

print("Target distribution %")
print(y.value_counts(normalize=True).round(2))

Target distribution
survived
0    549
1    342
Name: count, dtype: int64
********************
Target distribution %
survived
0    0.62
1    0.38
Name: proportion, dtype: float64

**Train Test Split**
- Train Set = Model Training
- Test Set = Model Testing

- X (Feature) = training_features (X_train),  test_features (X_test)
- y (Feature) = training_target (y_train),  test_target (y_test)

- train_test_split() divides the dataset into training and testing sets.

- X_train: Features used for training.
- X_test: Features used for testing.
- y_train: Target values used for training.
- y_test: Target values used for testing.
- test_size=0.2: 20% of data reserved for testing.
- random_state=42: Ensures reproducible results.
- stratify=y: Maintains the same class distribution in train and test sets (used mainly for classification problems).

In [14]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

In [15]:
print("Vector Shapes")
print("X_train", X_train.shape)
print("X_test", X_test.shape)
print("y_train", y_train.shape)
print("y_train", y_test.shape)

Vector Shapes
X_train (712, 12)
X_test (179, 12)
y_train (712,)
y_train (179,)

In [19]:
X_train[:5]

,pclass,sex,age,sibsp,parch,fare,embarked,class,adult_male,deck,embark_town,alone
692,3,male,NaN,0,0,56.4958,S,Third,True,NaN,Southampton,True
481,2,male,NaN,0,0,0.0000,S,Second,True,NaN,Southampton,True
527,1,male,NaN,0,0,221.7792,S,First,True,C,Southampton,True
855,3,female,18.0,0,1,9.3500,S,Third,False,NaN,Southampton,False
801,2,female,31.0,1,1,26.2500,S,Second,False,NaN,Southampton,False

In [20]:
y_train[:5]

692    1
481    0
527    0
855    1
801    1
Name: survived, dtype: int64

In [21]:
print(X_train.shape)
print(y_train.shape)

(712, 12)
(712,)

**Traing Process**
- The model is trained using the features: X_train, y_train (Find patterns and relationships between the two features)
- After training, the model is tested on X_test
- The model uses what it learned to generate predictions (y_pred).
- Compare the predicted values (y_pred) with the actual values (y_test).
- Calculate evaluation metrics to see how well the model performed.

In [25]:
print("Target distribution Full dataset")
print(y.value_counts())

print("*"*20)

print("Target distribution Full dataset %")
print(y.value_counts(normalize=True).round(2))

print("Target distribution Training set")
print(y_train.value_counts())

print("*"*20)

print("Target distribution Training set %")
print(y_train.value_counts(normalize=True).round(2))

print("Target distribution Test set")
print(y_test.value_counts())

print("*"*20)

print("Target distribution Test set %")
print(y_test.value_counts(normalize=True).round(2))

Target distribution Full dataset
survived
0    549
1    342
Name: count, dtype: int64
********************
Target distribution Full dataset %
survived
0    0.62
1    0.38
Name: proportion, dtype: float64
Target distribution Training set
survived
0    439
1    273
Name: count, dtype: int64
********************
Target distribution Training set %
survived
0    0.62
1    0.38
Name: proportion, dtype: float64
Target distribution Test set
survived
0    110
1     69
Name: count, dtype: int64
********************
Target distribution Test set %
survived
0    0.61
1    0.39
Name: proportion, dtype: float64

In [27]:
train_df = X_train.copy()
train_df[target_column] = y_train.values

test_df = X_test.copy()
test_df[target_column] = y_test.values

In [29]:
# Save to sheet
train_df.to_csv("train_df.csv", index=False)
test_df.to_csv("test_df.csv", index=False)